language: java
addons:
  sonarcloud:
    organization: inveasy
script:
- mvn clean install sonar:sonar -Dsonar.login=${SONAR_LOGIN} -B -V
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
deploy:
- provider: releases
  api_key:
    secure: CL25HvzxT2nLiTOcCKa+NMw2dMetcxbFURWO+uVkl6PQbqlqAaS7/qmdoCIKJzAGBZABSsM5bvdEoicmJi1n7n4PhTCoEqc+489V00z/yZWkC9yMg3W1pW2nWmZyHlFSUm3RULMQ7GzDKFtONp5mKbxfpo9aUCDlH/ypAPsAqx+faEMKn8BWQGy5g/2G3IAZFfJOp2xAjGnogxFyrhBdk5GaoRDy7ZBl6nQxEh/i95ZnsLFp0OdJHUFO5ag3WnXpY5V0yG27f8JDVtuSbazoiFd5/zMX+jXrwbAMkNhaneUGPm1dGrkxWcIC0p/ugu8+aaza3ZxOJcyr45kQmHUuNsfHiqiugrApJpTFIE0cXLA6WG3PVPlawaB7hJCRKwGb2+LOTFrwFI8HWbj/sTina//F/J2TIdXihbWRY9DXB8MsoHInRNIrFmeRwgK4PmrqtrWn5wa3gPRinjfEdY+LJmhE0xNAa/Jd8KHklMU5QcZ79hmoqiOdo6+xN9/T8+pYQnjp2DOwEv8xGUv5h7iBAN4Nwni10PENq/19tH9J/dQoBJ68N/jO9LFRLZ4U8wwo4tbHhyYsfvztu6R45j+NZ1C1y2JQv0/yzpoOsV5h1fUeIEYBMmLJ6o55tYYegXcWQnNmlo5jNhP1G7CsgGQWunRIH6zy7crr8auKkH/Qoi4=
  file_glob: true
  file: target/*.jar
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^[0-9]+\.[0-9]+\.[0-9]+$
    tags: true
- provider: bintray
  file: bintray-descriptor.json
  key:
    secure: dnia0FMKS5+KsWGHTmESWIpQpXxVM9CLIPWV5/+uPPPpqdLxHQvIrZFWh6lIxTeHsz068DYdMmgvbCOvJ+IIespUC5VxD4x00/fKgjB27h01QbzQrfzVRYHaTgfDZu6EA3nn5gstGrCC1Ra9FQzE+VIU0syJ59xekJQhKH/aEvyEgwuVu5YPeDrBe4Nm0rWOE2grFFlLNdPRzAzmCYp88d+XzuUSwpDXGthQRpcKiM8Xt/n4z345m8xczC29bhTLi07+wacati6PSYXbjZcWBVEmJypYXIX6pQZN+KTaetDgLWtaJlBdor19Oh/oDJTh8VbW8QFbI5as52MF4Kvr5Nu4Eza5weSPXrpxOcGIOwu3eUCSyaIC9CQysFsHHJ3esWjlIIk+Lcpzwn6fXDE4PyJJZa8fFiKiaFz4NQYOHy/IFnhrnDumxpMGJ/2a2+JO83gZCmsfj5hKfsWb5QJK42Lc3K20elR63Inwbof9KkCz7MduS/LJtDfZrIi4i06ycxiKgNT2pnFXST1b3pDNHcp9IOeWadKpjm5+Z+wfuVSkmAlZfRl2YsuykItQ4r83l3qCaZ7iA7P1TZ/90m8vFzJazEHQxTox2m7yCtHJP2F65iYlRDhUlw282cFzmN6uJsmAOuYoQh6rmHZEG9KbdA4foNY1C2B4NckXhzFXAJ4=
  user: goveranter
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^[0-9]+\.[0-9]+\.[0-9]+$
    tags: true